
# tap repositories and their packages

tap homebrew/bundle

tap homebrew/cask-fonts

tap argon/mas
brew mas

tap atlassian/tap
brew atlassian-plugin-sdk

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ack
brew autoconf
brew automake
brew cmake
brew ctags
brew fortune
brew fswatch
brew gdbm
brew gettext
brew git
brew go
brew gpg
brew libevent
brew libgpg-error
brew libksba
brew libtool
brew libyaml
brew makedepend
brew mono
brew netcat
brew node
brew openssl
brew pcre
brew pkg-config
brew pstree
brew python
brew readline
brew reattach-to-user-namespace
brew ruby
brew shellcheck
brew sqlite
brew telnet
brew the_silver_searcher
brew tmux
brew vim
brew watch
brew wget
brew xz
brew zsh

# Other Cask applications
cask alfred
cask docker
cask google-backup-and-sync
cask microsoft-teams
cask tastyworks
cask ubersicht

# App Store applications
appstore 417375580 BetterSnapTool
appstore 405399194 Kindle
appstore 482898991 LiveReload
appstore 715768417 Microsoft Remote Desktop
appstore 896450579 Textual 5
appstore 497799835 Xcode
